### ISSUE TITLE
Update of kubectl

### ISSUE THREAD

**Issue by sttts** [mesosphere/dcos-kubectl#2]
If a new package version is installed, the kubectl must be updated as well. Maybe we should version the kubectl binary in the .dcos dir.

**Comment by jdef** [comment]
I'd actually like the kubectl binaries to be hosted by the running
kubernetes framework, and let the dcos-kubernetes-cli download it from
there instead of from GH/releases

**Comment by sttts** [comment]
Good idea. Then it's the right build for sure. For that we have to cross-compile for all platforms in the dcos build scripts. /cc @karlkfi

**Comment by sttts** [comment]
Would you add the http handler to the apiserver for that? Or do we have any other accessible place to serve the binaries?

**Comment by jdef** [comment]
Either a nested nginx server, or use kubectl in proxy mode to serve static
content from a directory rather than the embedded stuff that apiserver is
built with. Should not be hard.

**Comment by sttts** [comment]
/xref https://github.com/mesosphere/kubernetes-mesos/tree/dcos_apiproxy_nginx_prototype

**Comment by sttts** [comment]
Done.
